In [1]:
from scipy.optimize import fsolve
from scipy.stats import norm, multivariate_normal
import numpy as np

# Q1

In [32]:
PD1 = 0.1
PD2 = 0.2
PD3 = 0.3
PDJ = 0.06

### Q1-1 Rho1,2

In [80]:
def f(x):
    inv_pd1 = norm.ppf(PD1)
    inv_pd2 = norm.ppf(PD2)
    y = multivariate_normal(mean=[0, 0], cov=[[1, x], [x, 1]]).cdf([inv_pd2, inv_pd1]) - PDJ
    return y

x = fsolve(f, 0)
print(x)

[0.60256967]


### Q1-2 Rho1,3

In [16]:
def f(x):
    inv_pd1 = norm.ppf(PD1)
    inv_pd2 = norm.ppf(PD3)
    y = multivariate_normal(mean=[0, 0], cov=[[1, x], [x, 1]]).cdf([inv_pd2, inv_pd1]) - PDJ
    return y

x = fsolve(f, 0)
print(x)

[0.43224727]


### Q1-3 Rho2,3

In [15]:
def f(x):
    inv_pd1 = norm.ppf(PD2)
    inv_pd2 = norm.ppf(PD3)
    y = multivariate_normal(mean=[0, 0], cov=[[1, x], [x, 1]]).cdf([inv_pd2, inv_pd1]) - PDJ
    return y

x = fsolve(f, 0)
print(x)

[0.]


# Q2

In [34]:
rho12 = 0.4
rho13 = 0.5
rho23 = 0.6
PD1 = 0.1
PD2 = 0.1
PD3 = 0.1

### Q2-1 PDJ12

In [35]:
def f(x):
    inv_pd1 = norm.ppf(PD1)
    inv_pd2 = norm.ppf(PD2)
    y = multivariate_normal(mean=[0, 0], cov=[[1, rho12], [rho12, 1]]).cdf([inv_pd2, inv_pd1]) - x
    return y

x = fsolve(f, 0)
print(x)

[0.02665351]


### Q2-2 PDJ13

In [20]:
def f(x):
    inv_pd1 = norm.ppf(PD1)
    inv_pd2 = norm.ppf(PD3)
    y = multivariate_normal(mean=[0, 0], cov=[[1, rho13], [rho13, 1]]).cdf([inv_pd2, inv_pd1]) - x
    return y

x = fsolve(f, 0)
print(x)

[0.03240152]


### Q2-3 PDJ23

In [21]:
def f(x):
    inv_pd1 = norm.ppf(PD2)
    inv_pd2 = norm.ppf(PD3)
    y = multivariate_normal(mean=[0, 0], cov=[[1, rho23], [rho23, 1]]).cdf([inv_pd2, inv_pd1]) - x
    return y

x = fsolve(f, 0)
print(x)

[0.03901747]


### Q2-4 PDJ123

In [22]:
def f(x):
    inv_pd1 = norm.ppf(PD1)
    inv_pd2 = norm.ppf(PD2)
    inv_pd3 = norm.ppf(PD3)
    y = multivariate_normal(mean=[0, 0, 0], cov=[[1, rho12, rho13], [rho12, 1, rho23], [rho13, rho23, 1]]).cdf([inv_pd2, inv_pd1, inv_pd3]) - x
    return y

x = fsolve(f, 0)
print(x)

[0.015533]


# Q3

In [56]:
PA1 = 1
PA2 = 1
PB1 = 0.5
PB2 = 0.7
PD1 = 0.1
PD2 = 0.2

In [57]:
inv_pd1 = norm.ppf(PD1)
inv_pd2 = norm.ppf(PD2)
inv_pa1 = norm.ppf(PA1)
inv_pa2 = norm.ppf(PA2)
inv_pb1 = norm.ppf(PB1)
inv_pb2 = norm.ppf(PB2)

In [59]:
prob_matrix = {'DD or worse': [inv_pd1, inv_pd2], 'DB or worse': [inv_pd1,inv_pb2], 'DA or worse': [inv_pd1, inv_pa2], 'BD or worse': [inv_pb1, inv_pd2], 'BB or worse': [inv_pb1,inv_pb2], 'BA or worse': [inv_pb1, inv_pa2], 'AD or worse': [inv_pa1, inv_pd2], 'AB or worse': [inv_pa1, inv_pb2],'AA or worse': [inv_pa1,inv_pa2] }

def f(x, prob):
    y = multivariate_normal(mean=[0, 0], cov=[[1, 0.4], [0.4, 1]]).cdf(prob) - x
    return y

prob_dis = {}
for key, item in prob_matrix.items():
    x = fsolve(f, 0, args=(item,))
    prob_dis[key] = x

prob_dis


{'DD or worse': array([0.04399001]),
 'DB or worse': array([0.09062698]),
 'DA or worse': array([0.1]),
 'BD or worse': array([0.14499531]),
 'BB or worse': array([0.40660958]),
 'BA or worse': array([0.5]),
 'AD or worse': array([0.2]),
 'AB or worse': array([0.7]),
 'AA or worse': array([1.])}

In [62]:
PDD = prob_dis['DD or worse']
PDD

array([0.04399001])

In [63]:
PDB = prob_dis['DB or worse'] - PDD
PDB

array([0.04663697])

In [69]:
PDA = prob_dis['DA or worse'] - PDB - PDD
PDA

array([0.00937302])

In [70]:
PBD = prob_dis['BD or worse'] - PDD
PBD

array([0.1010053])

In [72]:
PBB = prob_dis['BB or worse'] - PDB - PBD - PDD
PBB

array([0.2149773])

In [73]:
PBA = 0.4 - PBB - PBD
PBA

array([0.0840174])

In [74]:
PAD = 0.2 - PDD - PBD
PAD

array([0.05500469])

In [76]:
PAB = 0.5 - PDB - PBB
PAB

array([0.23838573])

In [78]:
PAA = 0.3 - PDA - PBA
PAA

array([0.20660958])

# Q4

In [83]:
PD1 = 0.01
PD2 = 0.02
PD3 = 0.03
PD4 = 0.04

PDJ = 0.001

### Q4-1 rho12

In [84]:
def f(x):
    inv_pd1 = norm.ppf(PD1)
    inv_pd2 = norm.ppf(PD2)
    y = multivariate_normal(mean=[0, 0], cov=[[1, x], [x, 1]]).cdf([inv_pd2, inv_pd1]) - PDJ
    return y

x = fsolve(f, 0)
print(x)

[0.31118614]


### Q4-2 rho13

In [85]:
def f(x):
    inv_pd1 = norm.ppf(PD1)
    inv_pd2 = norm.ppf(PD3)
    y = multivariate_normal(mean=[0, 0], cov=[[1, x], [x, 1]]).cdf([inv_pd2, inv_pd1]) - PDJ
    return y

x = fsolve(f, 0)
print(x)

[0.23718941]


### Q4-3 rho14

In [86]:
def f(x):
    inv_pd1 = norm.ppf(PD1)
    inv_pd2 = norm.ppf(PD4)
    y = multivariate_normal(mean=[0, 0], cov=[[1, x], [x, 1]]).cdf([inv_pd2, inv_pd1]) - PDJ
    return y

x = fsolve(f, 0)
print(x)

[0.18336735]


### Q4-4 rho23

In [87]:
def f(x):
    inv_pd1 = norm.ppf(PD2)
    inv_pd2 = norm.ppf(PD3)
    y = multivariate_normal(mean=[0, 0], cov=[[1, x], [x, 1]]).cdf([inv_pd2, inv_pd1]) - PDJ
    return y

x = fsolve(f, 0)
print(x)

[0.10050984]


### Q4-5 rho24

In [88]:
def f(x):
    inv_pd1 = norm.ppf(PD2)
    inv_pd2 = norm.ppf(PD4)
    y = multivariate_normal(mean=[0, 0], cov=[[1, x], [x, 1]]).cdf([inv_pd2, inv_pd1]) - PDJ
    return y

x = fsolve(f, 0)
print(x)

[0.04430853]


### Q4-6 rho34

In [89]:
def f(x):
    inv_pd1 = norm.ppf(PD3)
    inv_pd2 = norm.ppf(PD4)
    y = multivariate_normal(mean=[0, 0], cov=[[1, x], [x, 1]]).cdf([inv_pd2, inv_pd1]) - PDJ
    return y

x = fsolve(f, 0)
print(x)

[-0.03622908]


### Q4-7 corr and eigvals

In [93]:
corr = np.array([[1, 0.311, 0.237, 0.183], [0.311, 1, 0.101, 0.044], [0.237, 0.101, 1, -0.036], [0.183, 0.044, -0.036, 1]])
np.linalg.eigvals(corr)

array([1.4800558 , 0.60997814, 1.03560661, 0.87435946])